dist: xenial
language: go

go:
  - "1.12"

jobs:
  include:
    - stage: test
      script:
        - go test -cpu=1,2 -v ./...
    - script:
        - docker build -t concourse-slack-alert-resource-travis:$TRAVIS_BUILD_NUMBER .
        - echo "{\"source\":{\"url\":\"$(echo aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDBWRzdBTVNNL0JBV1FWUEhESy9MYUh5OVY4UTFrbXd2OERYdUdxazZIemYK | base64 -d)\"}}" | docker run -i
            -e "BUILD_TEAM_NAME=main"
            -e "BUILD_PIPELINE_NAME=travis-ci"
            -e "BUILD_JOB_NAME=test"
            -e "BUILD_NAME=$TRAVIS_BUILD_NUMBER"
            concourse-slack-alert-resource-travis:$TRAVIS_BUILD_NUMBER
            /opt/resource/out

branches:
  only:
    - master
