[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
